"""Repository classes and pydantic DTOs for paper_sorts database operations.

This module is the only place outside of models.py that may import SQLAlchemy.
Services depend on the DTO types defined here, never on ORM model types.

DTOs:
- PaperCreate: input for adding a new paper
- PaperSummary: output from search operations

Repositories:
- BibRepository: CRUD for the bib table
- PaperRepository: CRUD and search for the papers table
- AuthorRepository: CRUD for authors_id and authors_papers tables
"""

from __future__ import annotations

import logging
from typing import Sequence

from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session

from paper_sorts.db.models import Author, AuthorPaper, Bib, Paper

logger = logging.getLogger("paper_sorts.db.repositories")


# ---------------------------------------------------------------------------
# Pydantic DTOs
# ---------------------------------------------------------------------------


class PaperCreate(BaseModel):
    """Input DTO for creating a new paper entry.

    :param title: title of the publication
    :param contents: one-sentence summary of the paper
    :param bibtex_id: unique BibTeX citation key
    :param bibtex: full BibTeX source string
    :param authors: list of author names in "Last, First" format
    """

    title: str
    contents: str
    bibtex_id: str
    bibtex: str
    authors: list[str]


class PaperSummary(BaseModel):
    """Output DTO from search operations.

    :param paper_id: internal papers.id
    :param title: title of the publication
    :param contents: one-sentence summary
    :param bibtex_id: unique BibTeX citation key
    :param bibtex: full BibTeX source string
    :param authors: list of author names in "Last, First" format
    """

    paper_id: int
    title: str
    contents: str
    bibtex_id: str
    bibtex: str
    authors: list[str]


# ---------------------------------------------------------------------------
# Repository: Bib
# ---------------------------------------------------------------------------


class BibRepository:
    """Repository for the bib table (BibTeX entries).

    All SQL is generated by SQLAlchemy ORM/Core — no raw SQL strings.
    """

    def __init__(self, session: Session) -> None:
        """Initialise with an active SQLAlchemy session.

        :param session: active database session
        :type session: Session
        """
        self._session = session

    def get_by_id(self, bibtex_id: str) -> Bib | None:
        """Fetch a BibTeX entry by its primary key.

        :param bibtex_id: BibTeX citation key to look up
        :type bibtex_id: str
        :return: Bib ORM object, or None if not found
        :rtype: Bib | None
        """
        return self._session.get(Bib, bibtex_id)

    def exists(self, bibtex_id: str) -> bool:
        """Check whether a bibtex_id exists in the bib table.

        :param bibtex_id: BibTeX citation key to check
        :type bibtex_id: str
        :return: True if the key exists
        :rtype: bool
        """
        return self._session.get(Bib, bibtex_id) is not None

    def create(self, bibtex_id: str, bibtex: str) -> Bib:
        """Insert a new BibTeX entry into the bib table.

        :param bibtex_id: unique BibTeX citation key
        :type bibtex_id: str
        :param bibtex: full BibTeX source string
        :type bibtex: str
        :return: the newly created Bib ORM object
        :rtype: Bib
        """
        entry = Bib(bibtex_id=bibtex_id, bibtex=bibtex)
        self._session.add(entry)
        self._session.flush()
        return entry

    def update(self, bibtex_id: str, new_bibtex: str) -> Bib:
        """Update the bibtex string for an existing entry.

        :param bibtex_id: BibTeX citation key identifying the entry
        :type bibtex_id: str
        :param new_bibtex: new full BibTeX source string
        :type new_bibtex: str
        :return: updated Bib ORM object
        :rtype: Bib
        :raises ValueError: if bibtex_id does not exist in the table
        """
        entry = self.get_by_id(bibtex_id)
        if entry is None:
            raise ValueError(f"BibTeX entry '{bibtex_id}' not found in bib table")
        entry.bibtex = new_bibtex
        self._session.flush()
        return entry

    def delete(self, bibtex_id: str) -> None:
        """Delete a BibTeX entry from the bib table.

        :param bibtex_id: BibTeX citation key to delete
        :type bibtex_id: str
        :raises ValueError: if bibtex_id does not exist
        """
        entry = self.get_by_id(bibtex_id)
        if entry is None:
            raise ValueError(f"BibTeX entry '{bibtex_id}' not found")
        self._session.delete(entry)
        self._session.flush()


# ---------------------------------------------------------------------------
# Repository: Author
# ---------------------------------------------------------------------------


class AuthorRepository:
    """Repository for authors_id and authors_papers tables."""

    def __init__(self, session: Session) -> None:
        """Initialise with an active SQLAlchemy session.

        :param session: active database session
        :type session: Session
        """
        self._session = session

    def get_or_create(self, author_name: str) -> Author:
        """Return an existing Author record or create a new one.

        :param author_name: author name in "Last, First" format
        :type author_name: str
        :return: Author ORM object
        :rtype: Author
        """
        stmt = select(Author).where(Author.author == author_name)
        existing = self._session.execute(stmt).scalar_one_or_none()
        if existing is not None:
            return existing
        author = Author(author=author_name)
        self._session.add(author)
        self._session.flush()
        return author

    def link_author_to_paper(self, author_id: int, paper_id: int) -> None:
        """Create an authors_papers link between an author and a paper.

        :param author_id: id from authors_id table
        :type author_id: int
        :param paper_id: id from papers table
        :type paper_id: int
        """
        link = AuthorPaper(author_id=author_id, paper_id=paper_id)
        self._session.add(link)
        self._session.flush()

    def get_authors_for_paper(self, paper_id: int) -> list[str]:
        """Return a list of author names for the given paper.

        :param paper_id: papers.id to look up authors for
        :type paper_id: int
        :return: list of author names in "Last, First" format
        :rtype: list[str]
        """
        stmt = (
            select(Author.author)
            .join(AuthorPaper, AuthorPaper.author_id == Author.id)
            .where(AuthorPaper.paper_id == paper_id)
        )
        rows = self._session.execute(stmt).scalars().all()
        return list(rows)

    def get_by_name(self, author_name: str) -> Author | None:
        """Fetch an author by exact name.

        :param author_name: author name to look up
        :type author_name: str
        :return: Author ORM object or None
        :rtype: Author | None
        """
        stmt = select(Author).where(Author.author == author_name)
        return self._session.execute(stmt).scalar_one_or_none()

    def unlink_author_from_paper(self, author_id: int, paper_id: int) -> None:
        """Remove an author-paper link from authors_papers.

        :param author_id: authors_id.id
        :type author_id: int
        :param paper_id: papers.id
        :type paper_id: int
        """
        stmt = select(AuthorPaper).where(
            AuthorPaper.author_id == author_id,
            AuthorPaper.paper_id == paper_id,
        )
        link = self._session.execute(stmt).scalar_one_or_none()
        if link is not None:
            self._session.delete(link)
            self._session.flush()

    def author_has_other_papers(self, author_id: int, excluding_paper_id: int) -> bool:
        """Check whether an author has papers other than the specified one.

        :param author_id: authors_id.id
        :type author_id: int
        :param excluding_paper_id: paper_id to exclude from the check
        :type excluding_paper_id: int
        :return: True if the author is linked to at least one other paper
        :rtype: bool
        """
        stmt = select(AuthorPaper).where(
            AuthorPaper.author_id == author_id,
            AuthorPaper.paper_id != excluding_paper_id,
        )
        return self._session.execute(stmt).scalar_one_or_none() is not None

    def delete_author(self, author_id: int) -> None:
        """Delete an author record from authors_id.

        :param author_id: authors_id.id to delete
        :type author_id: int
        """
        stmt = select(Author).where(Author.id == author_id)
        author = self._session.execute(stmt).scalar_one_or_none()
        if author is not None:
            self._session.delete(author)
            self._session.flush()

    def update_author_name(self, author_id: int, new_name: str) -> None:
        """Update an author's name in the authors_id table.

        :param author_id: authors_id.id to update
        :type author_id: int
        :param new_name: new author name in "Last, First" format
        :type new_name: str
        :raises ValueError: if the author_id does not exist
        """
        stmt = select(Author).where(Author.id == author_id)
        author = self._session.execute(stmt).scalar_one_or_none()
        if author is None:
            raise ValueError(f"Author with id {author_id} not found")
        author.author = new_name
        self._session.flush()


# ---------------------------------------------------------------------------
# Repository: Paper
# ---------------------------------------------------------------------------


class PaperRepository:
    """Repository for the papers table with search operations."""

    def __init__(self, session: Session) -> None:
        """Initialise with an active SQLAlchemy session.

        :param session: active database session
        :type session: Session
        """
        self._session = session
        self._bib_repo = BibRepository(session)
        self._author_repo = AuthorRepository(session)

    def _build_summary(self, paper: Paper) -> PaperSummary:
        """Build a PaperSummary DTO from an ORM Paper object.

        :param paper: ORM Paper object
        :type paper: Paper
        :return: PaperSummary DTO with all fields populated
        :rtype: PaperSummary
        """
        bib = self._bib_repo.get_by_id(paper.bibtex_id)
        bibtex = bib.bibtex if bib else ""
        authors = self._author_repo.get_authors_for_paper(paper.id)
        return PaperSummary(
            paper_id=paper.id,
            title=paper.title,
            contents=paper.contents,
            bibtex_id=paper.bibtex_id,
            bibtex=bibtex,
            authors=authors,
        )

    def search_by_title(self, title: str) -> list[PaperSummary]:
        """Search for papers by exact title match.

        :param title: paper title to search for (exact match)
        :type title: str
        :return: list of PaperSummary DTOs for matching papers
        :rtype: list[PaperSummary]
        """
        stmt = select(Paper).where(Paper.title == title)
        papers: Sequence[Paper] = self._session.execute(stmt).scalars().all()
        return [self._build_summary(p) for p in papers]

    def search_by_author(self, author_name: str) -> list[PaperSummary]:
        """Search for papers by exact author name.

        :param author_name: author name in "Last, First" format (exact match)
        :type author_name: str
        :return: list of PaperSummary DTOs for papers by this author
        :rtype: list[PaperSummary]
        """
        stmt = (
            select(Paper)
            .join(AuthorPaper, AuthorPaper.paper_id == Paper.id)
            .join(Author, Author.id == AuthorPaper.author_id)
            .where(Author.author == author_name)
        )
        papers: Sequence[Paper] = self._session.execute(stmt).scalars().all()
        return [self._build_summary(p) for p in papers]

    def get_by_bibtex_id(self, bibtex_id: str) -> PaperSummary | None:
        """Fetch a paper by its BibTeX citation key.

        :param bibtex_id: BibTeX citation key
        :type bibtex_id: str
        :return: PaperSummary DTO or None if not found
        :rtype: PaperSummary | None
        """
        stmt = select(Paper).where(Paper.bibtex_id == bibtex_id)
        paper = self._session.execute(stmt).scalar_one_or_none()
        if paper is None:
            return None
        return self._build_summary(paper)

    def get_by_id(self, paper_id: int) -> PaperSummary | None:
        """Fetch a paper by its internal integer id.

        :param paper_id: papers.id value
        :type paper_id: int
        :return: PaperSummary DTO or None if not found
        :rtype: PaperSummary | None
        """
        paper = self._session.get(Paper, paper_id)
        if paper is None:
            return None
        return self._build_summary(paper)

    def create(self, paper_data: PaperCreate) -> PaperSummary:
        """Insert a new paper (bib + paper + author links) in one transaction.

        All operations use the shared session; the caller is responsible for
        committing via with_session context manager.

        :param paper_data: DTO with all required paper fields
        :type paper_data: PaperCreate
        :return: PaperSummary DTO for the newly created paper
        :rtype: PaperSummary
        :raises ValueError: if bibtex_id already exists in the bib table
        """
        if self._bib_repo.exists(paper_data.bibtex_id):
            raise ValueError(
                f"BibTeX key '{paper_data.bibtex_id}' already exists. "
                "Use a unique key or update the existing entry."
            )

        # Insert bib entry first (papers has FK → bib)
        self._bib_repo.create(paper_data.bibtex_id, paper_data.bibtex)

        # Insert paper record
        paper = Paper(
            title=paper_data.title,
            contents=paper_data.contents,
            bibtex_id=paper_data.bibtex_id,
        )
        self._session.add(paper)
        self._session.flush()  # flush to get paper.id

        # Link authors
        for author_name in paper_data.authors:
            author = self._author_repo.get_or_create(author_name)
            self._author_repo.link_author_to_paper(author.id, paper.id)

        return self._build_summary(paper)

    def update_title(self, paper_id: int, new_title: str) -> None:
        """Update the title of a paper.

        :param paper_id: papers.id to update
        :type paper_id: int
        :param new_title: new title string
        :type new_title: str
        :raises ValueError: if paper_id does not exist
        """
        paper = self._session.get(Paper, paper_id)
        if paper is None:
            raise ValueError(f"Paper with id {paper_id} not found")
        paper.title = new_title
        self._session.flush()

    def update_contents(self, paper_id: int, new_contents: str) -> None:
        """Update the summary/contents of a paper.

        :param paper_id: papers.id to update
        :type paper_id: int
        :param new_contents: new summary string
        :type new_contents: str
        :raises ValueError: if paper_id does not exist
        """
        paper = self._session.get(Paper, paper_id)
        if paper is None:
            raise ValueError(f"Paper with id {paper_id} not found")
        paper.contents = new_contents
        self._session.flush()

    def delete(self, paper_id: int) -> None:
        """Delete a paper and its bib entry; clean up orphaned authors.

        Deletes in this order to respect FK:
        1. Unlink all authors from this paper (authors_papers rows)
        2. Delete orphaned authors (authors with no remaining papers)
        3. Delete the paper row
        4. Delete the bib row

        :param paper_id: papers.id to delete
        :type paper_id: int
        :raises ValueError: if paper does not exist
        """
        paper = self._session.get(Paper, paper_id)
        if paper is None:
            raise ValueError(f"Paper with id {paper_id} not found")

        bibtex_id = paper.bibtex_id

        # Find all author links for this paper
        stmt = select(AuthorPaper).where(AuthorPaper.paper_id == paper_id)
        links = self._session.execute(stmt).scalars().all()

        for link in links:
            author_id = link.author_id
            self._session.delete(link)
            self._session.flush()
            # Delete author if they have no other papers
            if not self._author_repo.author_has_other_papers(author_id, paper_id):
                self._author_repo.delete_author(author_id)

        # Delete the paper row
        self._session.delete(paper)
        self._session.flush()

        # Delete the bib row
        self._bib_repo.delete(bibtex_id)
